### ISSUE TITLE
Xiaomi LYWSD02 BLE Sensor

### ISSUE THREAD

**Issue by JJussi** [Ernst79/sensor.mitemp_bt#1]
Hi!
Would it be "hard" to include LYWSD02 sensor to your code? Yes, I know that it uses bit different protocol than this one, but looking code https://github.com/h4/LYWSD02-home-assistant it's not that different.
I use hassio and your code is already part of hassio/HA. That LYWSD02 code don't work with standard hassio, because it uses different Bluetooth library.  And I'm not only one who is "waiting" working solution for that product. ;-)

**Comment by Ernst79** [comment]
I'm not sure, I don't have that device, so, hard to test things. 

This custom component is the result of the work of Magalex and tsymbaliuk (see https://community.home-assistant.io/t/xiaomi-mijia-bluetooth-temperature-humidity-sensor-compatibility/43568/228). First goal is to make the component available for the xiaomi mi temperature and humidity monitor, and get the instructions to install it more easily available for the community. Second goal is to get the component more in line with the Home Assistant structure. So, to be honest, I don't think it can be done in the near future, or somebody else should be willing to do this. Sorry. I'll leave it open for now.

**Comment by Magalex2x14** [comment]
@JJussi please look at https://github.com/custom-components/sensor.mitemp_bt/issues/7
