### ISSUE TITLE
Wrong negative temperature data parsing

### ISSUE THREAD

**Issue by Magalex2x14** [Ernst79/sensor.mitemp_bt#6]
Temperature is calculated as:
```python
((int(temperature_hex[2:4], 16) << 8) + int(temperature_hex[0:2], 16))/10
```
A simple left shift is the wrong method. Signed hex numbers come , and now, as a result, we have a large positive number.
For example, from 0xFFFF we get 6553.5, but it should be -0.1 ...

**Comment by Ernst79** [comment]
Fixed with #9
